# Generated by Django 4.2.13 on 2024-09-25 02:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.PositiveIntegerField()),
                ("step", models.CharField(max_length=100)),
                ("operation_type", models.CharField(max_length=100)),
                ("input_values", models.JSONField(encoder=api.models.NumpyEncoder)),
                (
                    "output_values",
                    models.JSONField(
                        blank=True, encoder=api.models.NumpyEncoder, null=True
                    ),
                ),
            ],
        ),
    ]
